server:
  port: 5555

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8500/eureka}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: storeModule
          uri: lb://STORE
          predicates:
            - Path=/store/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
