spring:
  application:
    name: 'provider'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8500/eureka}
server:
  port: 8502
  servlet:
    context-path: '/provider'
